<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI4LmuIE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI4LmuIE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI4LmuIE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI4LmuIE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI4LmuIE\App_KernelDevDebugContainer([
    'container.build_hash' => 'I4LmuIE',
    'container.build_id' => '667f9a65',
    'container.build_time' => 1579290578,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI4LmuIE');
